version: "3.3"

services:
  api:
    build: packages/api
    command: [ "flask", "run", "--host=0.0.0.0" ]
    volumes:
      - ./packages/api:/backend
      - /Users/gburns/Documents/2021H1:/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - 5001:5000
  nextjs:
    ports:
      - 3000:3000
    build:
      context: packages/client
      dockerfile: Dockerfile
    volumes:
      - ./packages/client:/frontend
      - /frontend/node_modules
      - /frontend/.next
    env_file:
      - .env
